version: '1'
services:
  envoygateway:
    build:
      context: .
      dockerfile: Envoy/Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:8080"